//-------------------------------- LOCALHOST APP --------------------------------//

//++++++++++++++++++++++++++++++++ seeds route ++++++++++++++++++++++++++++++++//
### get all seeds
GET http://localhost:3000/seeds

### get seed by ID
GET http://localhost:3000/seeds/62925506f94e79661b50f35c

### create new seed
POST http://localhost:3000/seeds HTTP/1.1
Content-Type: application/json

{
  "name": "Watermelon",
  "type": "",
  "seedsPerOunce": "250",
  "seedsPer100Feet": "1 oz",
  "sowingDepth": "1/4 inches",
  "daysToGermination": "10-14",
  "rowSpacing": "6-8 feet",
  "plantSpacing": "2-3 feet",
  "daysToHarvest": "75-90",
  "plantingDate": "Plant when soil is warm (after Memorial Day)."
}

### update seed by ID
PUT http://localhost:3000/seeds/pasteIdHere HTTP/1.1
Content-Type: application/json

{
  "name": "Watermelon",
  "type": "Yummy",
  "seedsPerOunce": "250",
  "seedsPer100Feet": "1 oz",
  "sowingDepth": "1/4 inches",
  "daysTogermination": "10-14",
  "rowSpacing": "6-8 feet",
  "plantSpacing": "2-3 feet",
  "daysToHarvest": "75-90",
  "plantingDate": "Plant when the soil is warm (after Memorial Day)."
}

### delete seed by ID
DELETE http://localhost:3000/seeds/pasteIdHere HTTP/1.1


//++++++++++++++++++++++++++++++++ garden-log route ++++++++++++++++++++++++++++++++//
### get all garden log entries
GET http://localhost:3000/garden-log

### get garden log entry by ID
GET http://localhost:3000/garden-log/62925506f94e79661b50f35c

### create new garden log entry
POST http://localhost:3000/garden-log HTTP/1.1
Content-Type: application/json

{
  "year": "2021",
  "seedName": "Peas",
  "seedType": "Snow",
  "variety": "Oregon Sugar Pod",
  "plantedQty": "20",
  "plantedDate": "05/28/2022",
  "harvestedQty": "15 lbs",
  "harvestedDate": "07/01/2022 - 08/01/2022",
  "notes": "Not my favorite. Won't plant again."
}

### update garden log entry by ID
PUT http://localhost:3000/garden-log/pasteIdHere HTTP/1.1
Content-Type: application/json

{
  "year": "2021",
  "seedName": "Peas",
  "seedType": "Snap",
  "variety": "Cascadia Dwarf",
  "plantedQty": "20",
  "plantedDate": "05/28/2022",
  "harvestedQty": "25 lbs",
  "harvestedDate": "07/01/2022 - 08/01/2022",
  "notes": "The kids ate them all before I could try them. Plant again next year."
}

### delete garden log entry by ID
DELETE http://localhost:3000/garden-log/pasteIdHere HTTP/1.1


//-------------------------------- HEROKU APP --------------------------------//

//++++++++++++++++++++++++++++++++ seeds route ++++++++++++++++++++++++++++++++//
### get all seeds
GET https://cfowl-garden.herokuapp.com/seeds

### get seed by ID
GET https://cfowl-garden.herokuapp.com/seeds/628924569bb4dc7e6f29a114

### create new seed
POST http://cfowl-garden.herokuapp.com/seeds HTTP/1.1
Content-Type: application/json

{
  "name": "Watermelon",
  "type": null,
  "seedsPerOunce": "250",
  "seedsPer100Feet": "1 oz",
  "sowingDepth": "1/4 inches",
  "daysTogermination": "10-14",
  "rowSpacing": "6-8 feet",
  "plantSpacing": "2-3 feet",
  "daysToHarvest": "75-90",
  "plantingDate": "Plant when soil is warm (after Memorial Day)."
}

### update seed by ID
PUT http://cfowl-garden.herokuapp.com/seeds/pasteIdHere HTTP/1.1
Content-Type: application/json

{
  "name": "Watermelon",
  "type": "Yummy",
  "seedsPerOunce": "250",
  "seedsPer100Feet": "1 oz",
  "sowingDepth": "1/4 inches",
  "daysTogermination": "10-14",
  "rowSpacing": "6-8 feet",
  "plantSpacing": "2-3 feet",
  "daysToHarvest": "75-90",
  "plantingDate": "Plant when the soil is warm (after Memorial Day)."
}

### delete seed by ID
DELETE http://cfowl-garden.herokuapp.com/seeds/pasteIdHere HTTP/1.1


//++++++++++++++++++++++++++++++++ garden-log route ++++++++++++++++++++++++++++++++//
### get all garden log entries
GET https://cfowl-garden.herokuapp.com/garden-log

### get garden log entry by ID
GET https://cfowl-garden.herokuapp.com/garden-log/628924569bb4dc7e6f29a114

### create new garden log entry
POST http://cfowl-garden.herokuapp.com/garden-log HTTP/1.1
Content-Type: application/json

{
  "year": "2021",
  "seedName": "Peas",
  "seedType": "Snow",
  "variety": "Oregon Sugar Pod",
  "plantedQty": "20",
  "plantedDate": "05/28/2022",
  "harvestedQty": "15 lbs",
  "harvestedDate": "07/01/2022 - 08/01/2022",
  "notes": "Not my favorite. Won't plant again."
}

### update garden log entry by ID
PUT http://cfowl-garden.herokuapp.com/garden-log/pasteIdHere HTTP/1.1
Content-Type: application/json

{
  "year": "2021",
  "seedName": "Peas",
  "seedType": "Snap",
  "variety": "Cascadia Dwarf",
  "plantedQty": "20",
  "plantedDate": "05/28/2022",
  "harvestedQty": "25 lbs",
  "harvestedDate": "07/01/2022 - 08/01/2022",
  "notes": "The kids ate them all before I could try them. Plant again next year."
}

### delete garden log entry by ID
DELETE http://cfowl-garden.herokuapp.com/garden-log/pasteIdHere HTTP/1.1